### ISSUE TITLE
Message queue sometimes stop processing messages

### ISSUE THREAD

**Issue by apa512** [ptaoussanis/carmine#122] opened 2014-12-11 12:26 UTC
Often my worker stops processing jobs after a while. No error message or anything, just keeps on running but without processing jobs. I have quite a heavy workload with 1000000 jobs that take about 5 seconds each running with 160 nthreads. I tried with as few as 20 threads but the problem remained. Any tips on how to debug this? Nothing happens for several hours so I doubt it's somehow related to backoff.

Here's my code, which I'm running with lein run:
```
(defn index-bucket [{:keys [mid message attempt]}]
  (println "Working on" message)
  (time
    (do-things)
    {:status :success})))

(def index-bucket-worker
  (car-mq/worker
    redis-conn
    "index-bucket"
    {:handler index-bucket
     :nthreads 160
     :auto-start false}))

(defn -main []
  (.addShutdownHook (Runtime/getRuntime) (Thread. #(stop-worker)))
  (start-worker))
```

**Comment by ptaoussanis** [comment] 2015-02-09 08:18
Closing this assuming you've found the cause of your trouble. Feel free to reopen if you're still having issues.

**Closed by ptaoussanis** 2015-02-09 08:18 UTC
